version: "3.4"

services:
  dev_links_info_crosver_api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev
    network_mode: "host"
    ports:
      - 8081:8081
      - 9229:9229

    volumes:
      - .:/usr/srv/links_info_crosver_api
