version: '3.4'

services:
  links_info_crosver_api:
    image: links_info_crosver_api
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8081
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 .